dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - google-chrome-beta
env:
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta
